# version: 2
# updates:
#   - package-ecosystem: "terraform"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "09:00"
#       timezone: "America/New_York"
#     open-pull-requests-limit: 10 
#     allow:
#       - dependency-type: "all"